### ISSUE TITLE
Python3 in docker container

### ISSUE THREAD

**Issue by jpaczia** [fzi-forschungszentrum-informatik/Lanelet2#108]
Installing and starting the docker container as described in the readme works flawless.
When I try to import lanelet2 in python3 I get the following output:

`
developer@6088b82874b5:~/workspace$ python3 -c "import lanelet2"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/developer/workspace/devel/lib/python2.7/dist-packages/lanelet2/__init__.py", line 12, in <module>
    module = import_module(__name__ + "." + module_name)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: dynamic module does not define module export function (PyInit_io) 
`

Importing lanelet2 in python2 works without any problems.

**Comment by poggenhans** [comment]
The docker container builds the python bindings only for the default python version of that distribution, which is python2 by default.

If you want it to build for python3, you would have to modify the Dockerfile so that it builds the bindings for python3, similar to the approach described in the [README](https://github.com/fzi-forschungszentrum-informatik/Lanelet2#python3).

**Comment by ConstantinB9** [comment]
For anyone looking for a Dockerfile to run python3 code, this one worked fine for me:

Changes from the original file:

Added Dependencies:
```
RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y \
        ...
	python-pip \
	python3-pip \
	python3-venv \
        ...
```
Created a virtual environment just like described in the [README](https://github.com/fzi-forschungszentrum-informatik/Lanelet2#python3)
```
# create virtual python environment
RUN pip install --user catkin_pkg  && pip3 install rospkg && python3 -m venv python3-env && /bin/bash -c "source python3-env/bin/activate"
```
`-DPYTHON_VERSION=3.6` added to catkin config
```
# setup workspace, add dependencies
RUN cd /home/developer/workspace \
    && /bin/bash -c "source /home/developer/.bashrc && catkin init && catkin config --cmake-args -DCMAKE_BUILD_TYPE=RelWithDebInfo -DPYTHON_VERSION=3.6" \
    && git clone https://github.com/KIT-MRT/mrt_cmake_modules.git /home/developer/workspace/src/mrt_cmake_modules
```

The complete Dockerfile:
```
ARG DISTRIBUTION=18.04
FROM ubuntu:${DISTRIBUTION} AS lanelet2_deps

ARG ROS_DISTRO=melodic

# basics
RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y \
	    bash-completion \
        build-essential \
	curl \
        git \
        cmake \
        ipython \
	keyboard-configuration \
	locales \
        lsb-core \
        nano \
        python-dev \
        software-properties-common \
        sudo \
	wget \
	python-pip \
	python3-pip \
	python3-venv \
	&& locale-gen en_US.UTF-8 \
        && apt-get clean && rm -rf /var/lib/apt/lists/*

# locale
ENV LANG=en_US.UTF-8 \
    LANGUAGE=en_US:en \
    LC_ALL=en_US.UTF-8 \
    ROS_DISTRO=${ROS_DISTRO}

# install ROS
RUN echo "deb http://packages.ros.org/ros/ubuntu $(lsb_release -sc) main" > /etc/apt/sources.list.d/ros-latest.list \
    && (apt-key adv --keyserver hkp://ha.pool.sks-keyservers.net:80 --recv-key C1CF6E31E6BADE8868B172B4F42ED6FBAB17C654 \
      || apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-key C1CF6E31E6BADE8868B172B4F42ED6FBAB17C654)

# dependencies for lanelet2
RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y \
        libboost-all-dev \
        libeigen3-dev \
        libgeographic-dev \
        libpugixml-dev \
        libpython-dev \
        libboost-python-dev \
        python-catkin-tools \
        ros-$ROS_DISTRO-catkin \
        ros-$ROS_DISTRO-rosbash \
        ros-$ROS_DISTRO-ros-environment # missing dep of rospack on xenial \
        && apt-get clean && rm -rf /var/lib/apt/lists/*

# create a user
RUN useradd --create-home --groups sudo --shell /bin/bash developer \
    && mkdir -p /etc/sudoers.d \
    && echo "developer ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/developer \
    && chmod 0440 /etc/sudoers.d/developer


# environment, dependencies and entry points
USER developer
ENV HOME /home/developer
WORKDIR /home/developer/workspace

RUN sudo chown -R developer:developer /home/developer \
    && echo "export ROS_HOSTNAME=localhost" >> /home/developer/.bashrc \
    && echo "source /opt/ros/$ROS_DISTRO/setup.bash" >> /home/developer/.bashrc \
    && echo "source /home/developer/workspace/devel/setup.bash" >> /home/developer/.bashrc

# create virtual python environment
RUN pip install --user catkin_pkg  && pip3 install rospkg && python3 -m venv python3-env && /bin/bash -c "source python3-env/bin/activate"

# setup workspace, add dependencies
RUN cd /home/developer/workspace \
    && /bin/bash -c "source /home/developer/.bashrc && catkin init && catkin config --cmake-args -DCMAKE_BUILD_TYPE=RelWithDebInfo -DPYTHON_VERSION=3.6" \
    && git clone https://github.com/KIT-MRT/mrt_cmake_modules.git /home/developer/workspace/src/mrt_cmake_modules

# second stage: get the code and build the image
FROM lanelet2_deps As lanelet2

# bring in the code
COPY --chown=developer:developer . /home/developer/workspace/src/lanelet2

# update dependencies
RUN git -C /home/developer/workspace/src/mrt_cmake_modules pull


# build
RUN /bin/bash -c "source /opt/ros/$ROS_DISTRO/setup.bash && catkin build"
```

**Comment by poggenhans** [comment]
On the `ament_support` branch, we now also suport building docker files with python3, based on ROS version used for the docker image.

**Comment by poggenhans** [comment]
The `ament_support` has been merged by now. You can build docker for ros2 e.g. like this: `docker build -t lanelet2 --build-arg=DISTRIBUTION=focal --build-arg=ROS_DISTRO=foxy --build-arg ROS=ros2 .`
